# Generated by Django 5.2.15 on 2026-06-17 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVO_CURSO', 'Nuevo curso asignado'), ('VENCIMIENTO_7D', 'Curso vence en 7 días'), ('VENCIMIENTO_1D', 'Curso vence mañana'), ('VENCIDO', 'Curso vencido'), ('EXAMEN_APROBADO', 'Examen aprobado'), ('EXAMEN_REPROBADO', 'Examen reprobado')], max_length=20, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='leída')),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID del recurso relacionado (Course, Enrollment, etc.).', null=True, verbose_name='ID de referencia')),
                ('referencia_tipo', models.CharField(blank=True, help_text="Modelo relacionado: 'course', 'enrollment', etc.", max_length=50, verbose_name='tipo de referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
