# Generated by Django 5.2.15 on 2026-06-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_area_model_and_userprofile_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rubrica',
            field=models.ImageField(blank=True, help_text='Imagen de la firma del capacitador. Una vez subida no se puede reemplazar.', null=True, upload_to='rubricas/', verbose_name='rúbrica (firma)'),
        ),
    ]
