# Generated by Django 5.2.15 on 2026-07-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_catalog_from_ad'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mfachallenge',
            new_name='mfa_challen_token_37f7e5_idx',
            old_name='mfa_challen_token_idx',
        ),
        migrations.RenameIndex(
            model_name='mfachallenge',
            new_name='mfa_challen_user_id_5cf428_idx',
            old_name='mfa_challen_user_used_idx',
        ),
    ]
