# Generated by Django 5.2.15 on 2026-06-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_minimo', models.PositiveSmallIntegerField(default=70, help_text='Porcentaje mínimo de respuestas correctas para considerar aprobado.', verbose_name='puntaje mínimo para aprobar (%)')),
                ('max_intentos', models.PositiveSmallIntegerField(default=3, verbose_name='máximo de intentos')),
                ('tiempo_limite_minutos', models.PositiveSmallIntegerField(blank=True, help_text='Null = sin límite de tiempo.', null=True, verbose_name='tiempo límite (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='courses.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'evaluación',
                'verbose_name_plural': 'evaluaciones',
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='enunciado')),
                ('tipo', models.CharField(choices=[('MULTIPLE_CHOICE', 'Selección única'), ('MULTIPLE_SELECT', 'Selección múltiple'), ('TRUE_FALSE', 'Verdadero / Falso')], default='MULTIPLE_CHOICE', max_length=20, verbose_name='tipo de pregunta')),
                ('opciones', models.JSONField(default=list, help_text='Lista de textos: ["Opción A", "Opción B", ...]', verbose_name='opciones')),
                ('respuesta_correcta', models.JSONField(help_text='MULTIPLE_CHOICE: índice entero (0-based). MULTIPLE_SELECT: lista de índices. TRUE_FALSE: boolean.', verbose_name='respuesta correcta')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('aprobada_por_humano', models.BooleanField(default=False, help_text='Solo las preguntas aprobadas por humano se incluyen en los exámenes.', verbose_name='aprobada por humano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment', verbose_name='evaluación')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'db_table': 'assessment_questions',
                'ordering': ['assessment', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento_numero', models.PositiveSmallIntegerField(verbose_name='número de intento')),
                ('respuestas_json', models.JSONField(default=dict, help_text='Guardado parcial mientras el examen está en curso.', verbose_name='respuestas')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='calificación (%)')),
                ('aprobado', models.BooleanField(blank=True, null=True, verbose_name='aprobado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment', verbose_name='evaluación')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='courses.enrollment', verbose_name='inscripción')),
            ],
            options={
                'verbose_name': 'intento de examen',
                'verbose_name_plural': 'intentos de examen',
                'db_table': 'user_answers',
                'ordering': ['enrollment', 'intento_numero'],
                'unique_together': {('enrollment', 'intento_numero')},
            },
        ),
    ]
