# Generated by Django 5.2.15 on 2026-06-17 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_area_model_and_userprofile_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido'), ('AUTOAPRENDIZAJE', 'Autoaprendizaje')], default='ONLINE', max_length=20, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('fecha_limite', models.DateField(blank=True, help_text='Opcional. Si se define, los enrollments sin completar se cierran automáticamente al vencer.', null=True, verbose_name='fecha límite')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='versión')),
                ('imagen_portada', models.CharField(blank=True, max_length=500, verbose_name='imagen de portada')),
                ('duracion_horas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duración (horas)')),
                ('cert_expira_meses', models.PositiveSmallIntegerField(blank=True, help_text='Cuántos meses es válido el certificado. Null = nunca expira.', null=True, verbose_name='expiración del certificado (meses)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='users.area', verbose_name='área')),
                ('audiencia_grupos', models.ManyToManyField(blank=True, related_name='courses', to='users.group', verbose_name='grupos objetivo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_as_instructor', to=settings.AUTH_USER_MODEL, verbose_name='instructor')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('VENCIDO', 'Vencido')], default='EN_PROGRESO', max_length=15, verbose_name='estado')),
                ('progreso_porcentaje', models.PositiveSmallIntegerField(default=0, verbose_name='progreso (%)')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inscripción')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'db_table': 'enrollments',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='fecha de emisión')),
                ('nota_obtenida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='nota obtenida')),
                ('url_pdf', models.CharField(blank=True, default='', max_length=500, verbose_name='URL del PDF')),
                ('url_qr', models.CharField(blank=True, default='', max_length=500, verbose_name='URL del QR')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='courses.course', verbose_name='curso')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='courses.enrollment', verbose_name='inscripción')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'db_table': 'certificates',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('tipo_contenido', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('TEXTO', 'Texto'), ('SCORM', 'SCORM')], max_length=10, verbose_name='tipo de contenido')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('es_secuencial', models.BooleanField(default=True, help_text='Si es True, el usuario debe completar el módulo N antes de abrir el N+1.', verbose_name='es secuencial')),
                ('duracion_minutos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='duración (minutos)')),
                ('url_video', models.URLField(blank=True, verbose_name='URL de video')),
                ('archivo_pdf', models.CharField(blank=True, max_length=500, verbose_name='archivo PDF')),
                ('contenido_html', models.TextField(blank=True, verbose_name='contenido HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'db_table': 'course_modules',
                'ordering': ['course', 'orden'],
                'unique_together': {('course', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completado')),
                ('last_position_json', models.JSONField(default=dict, help_text='Posición guardada: {second: N} para video, {page: N} para PDF, {scroll: N} para texto.', verbose_name='última posición')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.enrollment', verbose_name='inscripción')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.module', verbose_name='módulo')),
            ],
            options={
                'verbose_name': 'progreso de módulo',
                'verbose_name_plural': 'progreso de módulos',
                'db_table': 'module_progress',
                'unique_together': {('enrollment', 'module')},
            },
        ),
    ]
