# Generated by Django 5.2.15 on 2026-07-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_fix_virtual_tipo'),
        ('users', '0011_course_area_fk_to_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_owner', to='users.group', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
