# Generated by Django 5.2.15 on 2026-06-17 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='clave')),
                ('valor', models.TextField(blank=True, verbose_name='valor')),
                ('tipo_dato', models.CharField(choices=[('STRING', 'Texto'), ('BOOLEAN', 'Booleano'), ('INTEGER', 'Entero'), ('JSON', 'JSON')], default='STRING', max_length=20, verbose_name='tipo de dato')),
                ('categoria', models.CharField(choices=[('SMTP', 'Correo electrónico (SMTP)'), ('BRANDING', 'Identidad visual'), ('SEGURIDAD', 'Seguridad y contraseñas'), ('NOTIF', 'Notificaciones')], max_length=20, verbose_name='categoría')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('es_sensible', models.BooleanField(default=False, help_text='Si es True, el valor no se retorna en el API (ej. contraseñas SMTP).')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_changes', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'configuración del sistema',
                'verbose_name_plural': 'configuraciones del sistema',
                'db_table': 'system_settings',
                'ordering': ['categoria', 'clave'],
            },
        ),
    ]
